In [48]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.datasets import load_digits
digits = load_digits()

In [49]:
lr=LogisticRegression()
sv=SVC()
rf=RandomForestClassifier()

In [50]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(digits.data,digits.target,test_size=0.2)

### K Fold cross validation

####  How to use KFold

In [51]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [52]:
l=list(range(1,10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
for train_index,test_index in kf.split(l):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


### KFold for digits 

In [54]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [59]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_lr = []
scores_sv = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(lr, X_train, X_test, y_train, y_test))  
    scores_sv.append(get_score(sv, X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(rf, X_train, X_test, y_train, y_test))

E:\Coding\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
E:\Coding\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
E:\Coding\Anaconda\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
E:\Coding\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
E:\Coding\Anaconda\lib\site-packages\sklearn\linear_model\logist

In [65]:
scores_lr

[0.8953488372093024, 0.9499165275459098, 0.9093959731543624]

In [62]:
scores_sv

[0.39368770764119604, 0.41068447412353926, 0.4597315436241611]

In [63]:
scores_rf

[0.893687707641196, 0.8948247078464107, 0.924496644295302]